### ISSUE TITLE
[BUG] InvokeEndpointOutputTypeDef["Body"] and documentation disagree

### ISSUE THREAD

**Issue by torstenrudolf** [youtype/mypy_boto3_builder#112] opened 2021-10-07 11:19 UTC
**Describe the bug**
`mypy_boto3_sagemaker_runtime`'s type_defs.py defines `InvokeEndpointOutputTypeDef["Body"]` as having type `bytes`, but the [documentation](https://boto3.amazonaws.com/v1/documentation/api/1.18.54/reference/services/sagemaker-runtime.html#SageMakerRuntime.Client.invoke_endpoint) says it's `StreamingBody`.

**To Reproduce**

Run mypy on the following code sample

```
import boto3
from mypy_boto3_sagemaker_runtime.client import SageMakerRuntimeClient

sm: SageMakerRuntimeClient = boto3.client("sagemaker-runtime")
response = sm.invoke_endpoint(EndpointName="test",
                              ContentType="application/json",
                              Body=b"{}")

response["Body"].read()
```

Actual mypy output
```
test.py:9: error: "bytes" has no attribute "read"
Found 1 error in 1 file (checked 1 source file)
```

Expected mypy-output

Nothing.

**Additional context**

macos

installed "mypy-boto3-sagemaker-runtime==1.18.56" via poetry

**Comment by vemel** [comment] 2021-10-20 21:34
Output blobs always use `StreamingBody`. Thank you for the report! The new version `boto3-stubs 1.19.1` will be released tomorrow with the fix. Please let me know if it works as intended.

**Closed as completed** 2021-10-28 20:04 UTC
Labels: 🐞 bug, 👋 response needed, 🎉 released
