### ISSUE TITLE
boto3-stubs[iam,sts] from 1.24.24 to 1.24.43 upgrade breaking boto3 Session import

### ISSUE THREAD

**Issue by kingakimbrel** [youtype/mypy_boto3_builder#160] opened 2022-08-01 23:21 UTC
**Describe the bug**
In my poetry.lock before upgrade boto3-stubs[iam,sts] was set to 1.24.24 and project was working fine, after upgrade to 1.24.43 I started receiving following error from mypy 

```
error: Module "boto3"
has no attribute "Session"; maybe "session"?
    from boto3 import Session
    ^
```
 

**To Reproduce**

1. Install `boto3-stubs[iam,sts]@1.24.43`
2. Run `mypy`/`pyright` on the following code sample

```python
from boto3 import Session

...
```

**Actual output**

```
error: Module "boto3"
has no attribute "Session"; maybe "session"?
    from boto3 import Session
    ^
```

**Expected output**

Success

**Additional context**
Your OS, `boto3-stubs` installation method, `boto3` version, etc.

**Comment by vemel** [comment] 2022-08-02 12:42
Thank you for the report!

Fixed in `boto3-stubs 1.24.43.post1`. Please let me know if it works for you as it should.

**Comment by sarisia** [comment] 2022-08-03 06:33
I have the same issue.

Seems 1.24.43.post1 (and also 1.24.44) fixes `boto3.Session`, but not for `boto3.session.Session`,
which is described in [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session):

```python
import boto3

# OK
session = boto3.Session()

# NG
# (module) session
# "session" is not a known member of module Pylance(reportGeneralTypeIssues)
session2 = boto3.session.Session()
```

**Comment by vemel** [comment] 2022-08-03 09:58
Well, this is not the best way to use imported module. I will take a look if I can type this correctly.

**Comment by vemel** [comment] 2022-08-03 18:45
Fixed, should be included in `boto3-stubs 1.24.45` once it is out. Please check and let me know if it works as intended.

**Comment by vemel** [comment] 2022-08-03 22:40
@sarisa `boto3-stubs 1.24.45` is out. Please check.

**Comment by sarisia** [comment] 2022-08-04 02:41
@vemel checked 1.24.45 and `boto3.session.Session` is now working again.
Thank you for fixing the issue quickly!

**Comment by sarisia** [comment] 2022-08-04 02:51
@vemel sorry for bothering you again, but I'm just curious,
in commit https://github.com/youtype/mypy_boto3_builder/commit/68feda6629d6d80306452abe91cc373270797351,
why changing `import boto3.session as session` to `from boto3 import session as session`
fixes this kind of errors?

Is this a behaviour defined in somewhere in PEP, or is this just the implementation-specific
behaviour of pyright / pylance?

**Comment by vemel** [comment] 2022-08-04 10:43
I am not sure to be honest. But pyright looks happy with the second option. Maybe it makes sense to create a question/bug report in pyright repo.

**Comment by sarisia** [comment] 2022-08-04 19:04
OK, this seems really odd to me, so I'll raise an issue to Pyright later.
Thank you for maintaining this amazing project!

**Closed** 2022-08-04 19:21 UTC
Labels: 🐞 bug, 👋 response needed, 🎉 fix released
